timeLabels:
  - name: "Time: <1 Minute"
  - name: "Time: <5 Minutes"
  - name: "Time: <10 Minutes"
  - name: "Time: <15 Minutes"
  - name: "Time: <30 Minutes"
enableAccessControl:
  label: false
  organization: false
