name: UbiquiShirt Order Request Wizard
description: Order a UbiquiShirt using the DevPool Task OS
title: UbiquiShirt Order Request Wizard
body:
  - type: dropdown
    id: size
    attributes:
      label: Size
      description: What size would you like?
      options:
        - Small
        - Medium
        - Large
      default: 0
    validations:
      required: true
  - type: dropdown
    id: color
    attributes:
      label: What color would you like?
      options:
        - Black
        - White
    validations:
      required: true
  - type: textarea
    id: remarks
    attributes:
      label: Order remarks
      description: Do you have any extra remarks to add?
  - type: markdown
    attributes:
      value: |
        ### Last Step!
        
        ###### Set a TIME and PRIORITY label. 
          1. Look on the right side of the page (on the GitHub desktop web app client) under "Assignees" and above "Projects".
          2. Press the gear icon and search for "Time: " and select a "Time" label.
          3. Search for "Priority: " and select a "Priority" label.
