name: UbiquiShirt Order Request Wizard
description: Order a UbiquiShirt using the DevPool Task OS
title: UbiquiShirt Order Request Wizard
body:
  - type: dropdown
    id: size
    attributes:
      label: Size
      description: What size would you like?
      options:
        - Small
        - Medium
        - Large
      default: 0
    validations:
      required: true
  - type: dropdown
    id: color
    attributes:
      label: What color would you like?
      options:
        - Black
        - White
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        # Last Step!
        
        ### Set a TIME and PRIORITY label on this task! 
        1. Look on the right side of the page for "Labels" (under "Assignees" and above "Projects".) ![github com_ubiquity_ubiquibar_issues_new_assignees= labels= projects= template=ubiquishirt-order-wizard yml title=UbiquiShirt+Order+Request+Wizard](https://github.com/ubiquity/ubiquibar/assets/4975670/7fe44c98-5286-409f-be0d-c98b358e4d17)
        2. Press the gear icon and search for `Time: ` and select a `Time` label. ![github com_ubiquity_ubiquibar_issues_new_assignees= labels= projects= template=ubiquishirt-order-wizard yml title=UbiquiShirt+Order+Request+Wizard (1)](https://github.com/ubiquity/ubiquibar/assets/4975670/df8b952d-8367-49e0-8b2e-594778f349bc)
        3. Search for `Priority: ` and select a `Priority` label. ![github com_ubiquity_ubiquibar_issues_new_assignees= labels= projects= template=ubiquishirt-order-wizard yml title=UbiquiShirt+Order+Request+Wizard (2)](https://github.com/ubiquity/ubiquibar/assets/4975670/c1591952-c7a6-4c7f-9aef-d6a01ec11cef)







  - type: textarea
    id: remarks
    attributes:
      label: Order remarks
      description: Do you have any extra remarks to add?

