name: 🎒 UbiquiBag Order Request
description: Order a UbiquiBag using the DevPool Task OS
title: 🎒 UbiquiBag Order Request
labels: ["Priority: 4 (Urgent)", "Time: <5 Minutes"]
body:
  - type: dropdown
    id: color
    attributes:
      label: What color would you like?
      options:
        - Black
        - White
    validations:
      required: true
  - type: textarea
    id: remarks
    attributes:
      label: Order remarks
      description: Do you have any extra remarks to add?
